### ISSUE TITLE
Some sites don't work

### ISSUE THREAD

**Issue by ferraro** [AiondaDotCom/trashmail-addon#1]
Here are a couple examples of sites at which the TrashMail Firefox extension (4) doesn't work in FF57. TrashmMail 3 in Firefox 56 worked on these sites.

https://content.sixflags.com/contactus/updateaccount.aspx
https://www.annaaspnesdesigns.com/contact/

**Comment by Dreamsorcerer** [comment]
Ah, forgot about this. In the email field right?

It's this bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1345081

We can do a workaround for now, as it's still not fixed, by changing the context menu to appear in all contexts. This obviously means that it would now appear everywhere you click, rather than only editable regions.

**Comment by ferraro** [comment]
Could you maybe show it only if editable or if input type = "email"? That would be a workaround and not be so ugly. :-)

**Comment by Dreamsorcerer** [comment]
No, the only contexts available are listed here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/ContextType

Editable is the correct one, but as that bug report says, FF is incorrectly blocking a few input types. Once the bug is fixed, everything will be perfect. Until then, it's either missing in the email fields, or has to appear everywhere.

**Comment by ferraro** [comment]
Then we simply wait.

**Comment by Dreamsorcerer** [comment]
Note that the manual workaround for the enduser, is to generate the email in another field (e.g. the user field) and then copy it across.

**Comment by ferraro** [comment]
Yep, I guess they will fix it soon (I hope it so).
