### ISSUE TITLE
Firefox problem

### ISSUE THREAD

**Issue by Jaxxxon** [AiondaDotCom/trashmail-addon#4]
I'm using Firefox version 57.0.4.  I've tried everything to make trashmail work, but when using the Firefox browser addon it stalls at the login box; the green bar fills, but it doesn't go beyond that, & can't use it.

**Comment by Dreamsorcerer** [comment]
Just to double check. You're definitely talking about the addon installed from: https://addons.mozilla.org/en-GB/firefox/addon/trashmailnet/ ?

If so, could you send a screenshot where it gets stuck? Also, maybe you could try leaving it for 15 mins, to see if it times out; maybe it's caused by a network issue.

I don't think I've seen it hang before, as you describe.

**Comment by Jaxxxon** [comment]
Hi Sam – I think I finally figured out how to use the Trashmail Firefox addon.  However, Rosetta Stone doesn’t accept the generated email address garrick_strosin51@0box.eu<mailto:garrick_strosin51@0box.eu> as a valid email (I’m trying to see their free demo without getting a pile of mail from them later).

Thanks.

--Mike

**Comment by ferraro** [comment]
Please use as Plus member a hidden domain name.
